fix: deprecate python36 from chalice
aws/aws-encryption-sdk-python pull request #539
Opened 2022-12-22 09:34 UTC by ShubhamChaturvedi7

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

2023-01-06 13:38 UTC, ajewellamz approved these changes

2023-01-06 23:49 UTC, texastony requested changes
Unless there is a very good reason,
I think the Oracle's Tox should always use python3.9.

2023-01-06 23:49 UTC, texastony commented on decrypt_oracle/tox.ini
> +basepython = python3
Revert: Python3.9 is the latest version of Python AWS Lambda supports.
It behooves us to use the latest Python available, 
so we do not have to re-deploy the Lambda again when Python3.7 or 3.8 goes EOL.
```suggestion
basepython = python3.9
```

2023-01-06 23:49 UTC, texastony commented on decrypt_oracle/tox.ini
> +basepython = python3
```suggestion
basepython = python3.9
```

2023-01-06 23:49 UTC, texastony commented on decrypt_oracle/tox.ini
> +basepython = python3
```suggestion
basepython = python3.9
```

2023-01-06 23:49 UTC, texastony commented on decrypt_oracle/tox.ini
> +basepython = python3
```suggestion
basepython = python3.9
```

2023-01-09 22:25 UTC, texastony approved these changes

2023-01-09 22:25 UTC, merged