chore(CFN): Allow access to CI keystore resources from CI and release roles
aws/aws-encryption-sdk-python pull request #637
Opened 2024-02-08 22:01 UTC by lucasmcdonald3

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

2024-02-08 22:08 UTC, ajewellamz approved these changes

2024-02-08 22:10 UTC, josecorella approved these changes

2024-03-15 01:13 UTC, texastony requested changes

2024-03-15 01:13 UTC, texastony commented on cfn/Public-ESDK-Python-CI.yml
> +    Default: HierarchicalKeyringTestTable
Blocking: Remove unused Parameter
```suggestion
```

2024-03-15 01:13 UTC, texastony commented on cfn/Public-ESDK-Python-CI.yml
> +    Default: KeyStoreTestTable
Blocking: Remove unused Parameter
```suggestion
```

2024-03-15 01:13 UTC, texastony commented on cfn/Public-ESDK-Python-CI.yml
> +Description: "DDB Table and IAM Managed Policies/Role for AWS KMS Hierarchical Keyring Testing"
```suggestion
Description: "IAM Managed Policies/Role for AWS KMS Hierarchical Keyring Testing"
```

2024-03-15 03:05 UTC, texastony approved these changes

2024-03-18 16:21 UTC, lucasmcdonald3 commented on cfn/Public-ESDK-Python-CI.yml
> +    Description: A prefix that will be applied to any names
```suggestion
    Description: A prefix that will be applied to any resource names
```

2024-03-18 16:21 UTC, lucasmcdonald3 commented on cfn/Public-ESDK-Python-CI.yml
> +    Description: A prefix that will be applied to any names
(just restarting CI)

2024-03-18 17:15 UTC, merged